#Start with pathogen FASTA file or amino acid tbl
pathogen_input: "aa_tbl" #or fasta
tool: 'PLINK' #or regenie

#File Paths (When Pathogen input is fasta)
pathogen_gff: ""
pathogen_ref: ""
pathogen_fasta: ""

#File Paths
host_VCF: "../raw_data/host/G2G_Test.vcf.gz"
covar_file: "../raw_data/Test_Covars.txt"
pathogen_tbl_dir: "../raw_data/pathogen/AA_Table/"

#Host Parameters
host_MAF: 0.05
host_missing: 0.1
host_HWE: 1e-6
N_PC: 5
excl_chr6: true   #Whether to include chr6 when calculating PCA 

#Pathogen Parameters
pPCA: false #Standard or phylogenetic PC (Tree required)
N_pPC: 5
pathogen_MAC: 5
pathogen_missing: 0.1
genes: "" #Keep empty to run all genes

#Tree file in newwick(When pPCA is true)
nw_file: ""
